### ISSUE TITLE
Option to disable logging to console when syncing/updating data

### ISSUE THREAD

**Issue by plibither8** [bfred-it/webext-options-sync#17]
Hey :wave:

`opts.syncForm()` logs the updates to the console every time the form data has changed. When this is used in content scripts (as opposed to background/popup/options scripts) it (in my opinion) pollutes the console. I suggest add logging to the console as an "option" passed to the syncForm function as an optional argument like so:

```js
// This is an optional argument
// Default value can be `true` as it currently is
const options = {
	logging: false;
};

opts.syncForm(form, options);
```

Cheers,

Mihir

**Comment by bfred-it** [comment]
Makes sense! It can be added as an option to `new OptionSync(key, {logging: false})` so it's shared across all the methods.

**Comment by plibither8** [comment]
Yeah, that can be done too!

Should I create a PR for this? I have looked at code and I'm guessing it's a simple `if (logging === true)` check that we need to add before logging any info/warning to the console.

**Comment by bfred-it** [comment]
It's probably best to have an overridable logging function so we don't have to use `if` every time. Something like:

```diff
	constructor(options) {
		this.storageName = options.storageName || 'options';
		if (options.logging === false) {
			this.log = () => {};
		}
	}
	log() {
		console.log(...arguments);
	}
```

**Comment by plibither8** [comment]
Yes of course, much neater.

**Comment by plibither8** [comment]
Hey, I'm having some trouble getting the `_log` function correctly called from other methods in the class. The constructor and log function:

```js
constructor(options = {}) {
	this.storageName = options.storageName || 'options';
	if (options.logging === false) {
		this._log = () => {};
	}
}
	
_log(method, list = []) {
	console[method](...list);
}
```

and it should be called like so:
```js
this._log('info', ['Current options:', options]);
```

However, I'm getting the following TypeError when trying it on an extension of my own locally:
```
Uncaught (in promise) TypeError: this._log is not a function
    at Function._applyToForm (content.js:188)
```

I'm guessing it's got to do with the scope of `this` changing, but I'm not sure.

**Comment by bfred-it** [comment]
Ah yeah because `_applyToForm` is a static method. You can changed it to be a regular method and change its calls from `OptionsSync._applyToForm` to `this._applyToForm`

Also 

```diff
- _log(method, list = []) {
+ _log(method, ...args) {
```

And 
```diff
- this._log("info", ["Current options:", options]);
+ this._log('info', 'Current options:', options);
```

**Comment by plibither8** [comment]
Thanks! Please publish to npm too :relaxed:
