### ISSUE TITLE
Validate inputs before saving

### ISSUE THREAD

**Issue by ramlmn** [bfred-it/webext-options-sync#2]
It would be a good idea to implement user input validation before saving for each `input` or `change` event. Like by simply checking `validity.valid` property of inputs.

#### Use case:
Imagine having an input with input type email or url that need to be validated before saving. If the data is saved without validation, they have to be re-validated again after retrieving.

**Comment by bfred-it** [comment]
I like this! As long as you inform the user somehow, otherwise they'd think it's saved but it isn't. Maybe via the `:invalid` CSS selector.

PRs to `_handleFormUpdates()` welcome :)

**Comment by ramlmn** [comment]
I am thinking of working on this.

Do you thing if it would be better to validate by default or pass it in as options in `constructor`. If we wanted to pass in options through `constructor` that would break the current API where it currently takes in a string i.e. `storageName`.

I'm also thinking of adding class name like `is-invalid` if that would help, or just use `:invalid` selector.

**Comment by bfred-it** [comment]
I don't think it needs any option. If you want validation you use HTML attributes, otherwise you don't.

`:valid`/`:invalid` also seem enough:

![a](https://user-images.githubusercontent.com/1402241/27991833-377f3042-64b6-11e7-94cc-4a79abcc37e7.gif)

https://css-tricks.com/almanac/selectors/v/valid/

**Comment by ramlmn** [comment]
Actually, currently the code saves the values when they are changed. I was thinking more or less to validate the inputs before saving.

This code should explain what I'm trying to say:
``` js
constructor(possibleOptions = {}) {
	if (typeof possibleOptions === 'string') {
		this.options = Object.assign({}, this.defaults, {storageName: possibleOptions});
	} else {
		this.options = Object.assign({}, this.defaults, possibleOptions);
	}

	this.storage = chrome.storage.sync || chrome.storage.local;  
}

get defaults() {
	return {
		validateBeforeSave: true,
		storageName: 'options'
	};
}

// ...

setAll(newOptions) {
	return new Promise(resolve => {
		this.storage.set({
			[this.options.storageName]: newOptions,
		}, resolve);
	});
}

// ...

_handleFormUpdates(e) {
	const el = e.target;
	const name = el.name;
	let value = el.value;

	// ...

	if (this.options.validateBeforeSave && el.validity.valid) {
		return; // <- We don't save it
	}

	console.info('Saving option', el.name, 'to', value);
	this.set({
		[name]: value,
	});
}
```

The code looks tacky, but needs help.

**Comment by bfred-it** [comment]
We only need this, **no options**:

```js
	if (el.validity.valid) {
		return; // <- We don't save it
	}
```

**Comment by bfred-it** [comment]
Thanks to #3, validation is in 0.12.0!
