### ISSUE TITLE
Text boxes lose keypresses if you type quickly

### ISSUE THREAD

**Issue by chris-morgan** [bfred-it/webext-options-sync#22]
See https://github.com/plibither8/refined-hacker-news/issues/41. Filing here at the suggestion of there.

**Comment by bfred-it** [comment]
Yeah I noticed that there’s a feedback loop. 

1. You type
1. WOS saves
1. WOS detects a change
1. WOS updates the form with the “new” content

**Comment by bfred-it** [comment]
A simple fix would be to avoid updating the field if it’s focused. 

A full fix, later, would be to stop the field update if the “changed” event comes from the same page, if possible.
