### ISSUE TITLE
Use <form is="options-sync"> as a sync activator

### ISSUE THREAD

**Issue by bfred-it** [bfred-it/webext-options-sync#7]
Similar to what https://github.com/kui/storage-form does

**Comment by sindresorhus** [comment]
Agreed. Should still support programmatic activation though.

**Comment by bfred-it** [comment]
This would only replace the `syncForm` method, when would the programmatic activation be needed?

**Comment by sindresorhus** [comment]
I was thinking dynamically generated forms, but I guess you could add the attribute dynamically too.
