### ISSUE TITLE
Full clear options

### ISSUE THREAD

**Issue by icetee** [bfred-it/webext-options-sync#9]
During development I have defined a bad property name and there is no way to delete it all.

This code helped me, but if accidental would have been published it would have stuck to the clients.
```javascript
const options = { ... };

chrome.storage.sync.clear();
chrome.storage.sync.set({options});
```

The wrong settings were exception this line.
https://github.com/bfred-it/webext-options-sync/blob/205fe0743d34ddca1a4066b1124145adea2ac653/webext-options-sync.js#L108

Could it be automatically removed from storage in such a case?

**Comment by bfred-it** [comment]
Checkout the included `removeUnused` migration. More info in the readme
